# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BeeminderSettings(object):
    def setupUi(self, BeeminderSettings):
        BeeminderSettings.setObjectName("BeeminderSettings")
        BeeminderSettings.resize(539, 501)
        self.gridLayoutWidget = QtWidgets.QWidget(BeeminderSettings)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 521, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.top_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.top_gridLayout.setContentsMargins(11, 11, 11, 11)
        self.top_gridLayout.setSpacing(6)
        self.top_gridLayout.setObjectName("top_gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.gridLayoutWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.top_gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.enabled = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.enabled.setEnabled(True)
        self.enabled.setCheckable(True)
        self.enabled.setObjectName("enabled")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.enabled)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 461, 118))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.general_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.general_gridLayout.setContentsMargins(11, 11, 11, 11)
        self.general_gridLayout.setSpacing(6)
        self.general_gridLayout.setObjectName("general_gridLayout")
        self.shutdown = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.shutdown.setEnabled(True)
        self.shutdown.setChecked(True)
        self.shutdown.setObjectName("shutdown")
        self.general_gridLayout.addWidget(self.shutdown, 2, 0, 1, 1)
        self.token = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.token.setObjectName("token")
        self.general_gridLayout.addWidget(self.token, 1, 0, 1, 1)
        self.username_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.username_label.setObjectName("username_label")
        self.general_gridLayout.addWidget(self.username_label, 0, 1, 1, 1)
        self.username = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.username.setObjectName("username")
        self.general_gridLayout.addWidget(self.username, 0, 0, 1, 1)
        self.token_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.token_label.setObjectName("token_label")
        self.general_gridLayout.addWidget(self.token_label, 1, 1, 1, 1)
        self.ankiweb = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.ankiweb.setObjectName("ankiweb")
        self.general_gridLayout.addWidget(self.ankiweb, 3, 0, 1, 1)
        self.goals_toolBox = QtWidgets.QToolBox(self.enabled)
        self.goals_toolBox.setGeometry(QtCore.QRect(10, 160, 501, 281))
        self.goals_toolBox.setObjectName("goals_toolBox")
        self.time_page = QtWidgets.QWidget()
        self.time_page.setGeometry(QtCore.QRect(0, 0, 501, 188))
        self.time_page.setObjectName("time_page")
        self.time_enabled = QtWidgets.QGroupBox(self.time_page)
        self.time_enabled.setGeometry(QtCore.QRect(10, 0, 491, 191))
        self.time_enabled.setCheckable(True)
        self.time_enabled.setObjectName("time_enabled")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.time_enabled)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 431, 161))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.time_slug_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.time_slug_label.setObjectName("time_slug_label")
        self.gridLayout.addWidget(self.time_slug_label, 2, 1, 1, 1)
        self.time_units = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.time_units.setObjectName("time_units")
        self.time_units.addItem("")
        self.time_units.addItem("")
        self.time_units.addItem("")
        self.gridLayout.addWidget(self.time_units, 3, 0, 1, 1)
        self.time_units_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.time_units_label.setObjectName("time_units_label")
        self.gridLayout.addWidget(self.time_units_label, 3, 1, 1, 1)
        self.time_premium = QtWidgets.QGroupBox(self.gridLayoutWidget_2)
        self.time_premium.setCheckable(True)
        self.time_premium.setChecked(True)
        self.time_premium.setObjectName("time_premium")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.time_premium)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 350, 52))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.time_premium_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.time_premium_gridLayout.setContentsMargins(11, 11, 11, 11)
        self.time_premium_gridLayout.setSpacing(6)
        self.time_premium_gridLayout.setObjectName("time_premium_gridLayout")
        self.time_agg = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.time_agg.setObjectName("time_agg")
        self.time_agg.addItem("")
        self.time_agg.addItem("")
        self.time_premium_gridLayout.addWidget(self.time_agg, 1, 0, 1, 1)
        self.time_agg_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.time_agg_label.setObjectName("time_agg_label")
        self.time_premium_gridLayout.addWidget(self.time_agg_label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.time_premium, 6, 0, 1, 1)
        self.time_slug = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.time_slug.setObjectName("time_slug")
        self.gridLayout.addWidget(self.time_slug, 2, 0, 1, 1)
        self.goals_toolBox.addItem(self.time_page, "")
        self.reviewed_page = QtWidgets.QWidget()
        self.reviewed_page.setGeometry(QtCore.QRect(0, 0, 501, 188))
        self.reviewed_page.setObjectName("reviewed_page")
        self.reviewed_enabled = QtWidgets.QGroupBox(self.reviewed_page)
        self.reviewed_enabled.setGeometry(QtCore.QRect(10, 0, 491, 181))
        self.reviewed_enabled.setCheckable(True)
        self.reviewed_enabled.setObjectName("reviewed_enabled")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.reviewed_enabled)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(20, 20, 431, 131))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.reviewed_slug_label = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.reviewed_slug_label.setObjectName("reviewed_slug_label")
        self.gridLayout_4.addWidget(self.reviewed_slug_label, 2, 1, 1, 1)
        self.reviewed_premium = QtWidgets.QGroupBox(self.gridLayoutWidget_7)
        self.reviewed_premium.setCheckable(True)
        self.reviewed_premium.setChecked(True)
        self.reviewed_premium.setObjectName("reviewed_premium")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.reviewed_premium)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(10, 30, 350, 52))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.reviewed_agg = QtWidgets.QComboBox(self.gridLayoutWidget_8)
        self.reviewed_agg.setObjectName("reviewed_agg")
        self.reviewed_agg.addItem("")
        self.reviewed_agg.addItem("")
        self.gridLayout_5.addWidget(self.reviewed_agg, 1, 0, 1, 1)
        self.reviewed_agg_label = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.reviewed_agg_label.setObjectName("reviewed_agg_label")
        self.gridLayout_5.addWidget(self.reviewed_agg_label, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.reviewed_premium, 5, 0, 1, 1)
        self.reviewed_slug = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.reviewed_slug.setObjectName("reviewed_slug")
        self.gridLayout_4.addWidget(self.reviewed_slug, 2, 0, 1, 1)
        self.goals_toolBox.addItem(self.reviewed_page, "")
        self.added_page = QtWidgets.QWidget()
        self.added_page.setGeometry(QtCore.QRect(0, 0, 501, 188))
        self.added_page.setObjectName("added_page")
        self.added_enabled = QtWidgets.QGroupBox(self.added_page)
        self.added_enabled.setGeometry(QtCore.QRect(10, 0, 491, 191))
        self.added_enabled.setCheckable(True)
        self.added_enabled.setObjectName("added_enabled")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.added_enabled)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 20, 431, 161))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.added_slug_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.added_slug_label.setObjectName("added_slug_label")
        self.gridLayout_3.addWidget(self.added_slug_label, 2, 1, 1, 1)
        self.added_premium = QtWidgets.QGroupBox(self.gridLayoutWidget_5)
        self.added_premium.setCheckable(True)
        self.added_premium.setChecked(True)
        self.added_premium.setObjectName("added_premium")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.added_premium)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 30, 350, 52))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.premium_gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.premium_gridLayout.setContentsMargins(11, 11, 11, 11)
        self.premium_gridLayout.setSpacing(6)
        self.premium_gridLayout.setObjectName("premium_gridLayout")
        self.added_agg = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.added_agg.setObjectName("added_agg")
        self.added_agg.addItem("")
        self.added_agg.addItem("")
        self.premium_gridLayout.addWidget(self.added_agg, 1, 0, 1, 1)
        self.added_agg_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.added_agg_label.setObjectName("added_agg_label")
        self.premium_gridLayout.addWidget(self.added_agg_label, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.added_premium, 5, 0, 1, 1)
        self.added_slug = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.added_slug.setObjectName("added_slug")
        self.gridLayout_3.addWidget(self.added_slug, 2, 0, 1, 1)
        self.added_type = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        self.added_type.setObjectName("added_type")
        self.added_type.addItem("")
        self.added_type.addItem("")
        self.gridLayout_3.addWidget(self.added_type, 3, 0, 1, 1)
        self.added_type_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.added_type_label.setObjectName("added_type_label")
        self.gridLayout_3.addWidget(self.added_type_label, 3, 1, 1, 1)
        self.goals_toolBox.addItem(self.added_page, "")
        self.top_gridLayout.addWidget(self.enabled, 1, 0, 1, 1)

        self.retranslateUi(BeeminderSettings)
        self.goals_toolBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(BeeminderSettings)
        BeeminderSettings.setTabOrder(self.enabled, self.time_slug)
        BeeminderSettings.setTabOrder(self.time_slug, self.time_units)
        BeeminderSettings.setTabOrder(self.time_units, self.time_premium)
        BeeminderSettings.setTabOrder(self.time_premium, self.time_agg)

    def retranslateUi(self, BeeminderSettings):
        _translate = QtCore.QCoreApplication.translate
        BeeminderSettings.setWindowTitle(_translate("BeeminderSettings", "Beeminder Settings"))
        self.enabled.setTitle(_translate("BeeminderSettings", "Enable Beeminder sync"))
        self.shutdown.setText(_translate("BeeminderSettings", "Sync at shutdown"))
        self.username_label.setText(_translate("BeeminderSettings", "Username"))
        self.token_label.setText(_translate("BeeminderSettings", "API key"))
        self.ankiweb.setText(_translate("BeeminderSettings", "Sync after synchronizing with AnkiWeb"))
        self.time_enabled.setTitle(_translate("BeeminderSettings", "Enable this goal"))
        self.time_slug_label.setText(_translate("BeeminderSettings", "Goalname"))
        self.time_units.setItemText(0, _translate("BeeminderSettings", "hours"))
        self.time_units.setItemText(1, _translate("BeeminderSettings", "minutes"))
        self.time_units.setItemText(2, _translate("BeeminderSettings", "seconds"))
        self.time_units_label.setText(_translate("BeeminderSettings", "Goal units"))
        self.time_premium.setTitle(_translate("BeeminderSettings", "Use premium features"))
        self.time_agg.setItemText(
            0, _translate("BeeminderSettings", "overwrite the datapoint (use with aggday \"sum\")")
        )
        self.time_agg.setItemText(
            1, _translate("BeeminderSettings", "keep multiple datapoints (use with \"last\", \"max\", ...)")
        )
        self.time_agg_label.setText(_translate("BeeminderSettings", "Behaviour when syncing multiple times in one day"))
        self.goals_toolBox.setItemText(
            self.goals_toolBox.indexOf(self.time_page), _translate("BeeminderSettings", "Sync review time")
        )
        self.reviewed_enabled.setTitle(_translate("BeeminderSettings", "Enable this goal"))
        self.reviewed_slug_label.setText(_translate("BeeminderSettings", "Goalname"))
        self.reviewed_premium.setTitle(_translate("BeeminderSettings", "Use premium features"))
        self.reviewed_agg.setItemText(
            0, _translate("BeeminderSettings", "overwrite the datapoint (use with aggday \"sum\")")
        )
        self.reviewed_agg.setItemText(
            1, _translate("BeeminderSettings", "keep multiple datapoints (use with \"last\", \"max\", ...)")
        )
        self.reviewed_agg_label.setText(
            _translate("BeeminderSettings", "Behaviour when syncing multiple times in one day")
        )
        self.goals_toolBox.setItemText(
            self.goals_toolBox.indexOf(self.reviewed_page), _translate("BeeminderSettings", "Sync number of reviews")
        )
        self.added_enabled.setTitle(_translate("BeeminderSettings", "Enable this goal"))
        self.added_slug_label.setText(_translate("BeeminderSettings", "Goalname"))
        self.added_premium.setTitle(_translate("BeeminderSettings", "Use premium features"))
        self.added_agg.setItemText(
            0, _translate("BeeminderSettings", "overwrite the datapoint (use with aggday \"sum\")")
        )
        self.added_agg.setItemText(
            1, _translate("BeeminderSettings", "keep multiple datapoints (use with \"last\", \"max\", ...)")
        )
        self.added_agg_label.setText(
            _translate("BeeminderSettings", "Behaviour when syncing multiple times in one day")
        )
        self.added_type.setItemText(0, _translate("BeeminderSettings", "cards"))
        self.added_type.setItemText(1, _translate("BeeminderSettings", "notes"))
        self.added_type_label.setText(_translate("BeeminderSettings", "Type"))
        self.goals_toolBox.setItemText(
            self.goals_toolBox.indexOf(self.added_page), _translate("BeeminderSettings", "Sync number of additions")
        )
